%% Data
% Starting from the difference equation of the filter, it's possible to compute
% the transfer function as
% tf = (1/4 z^-4 -1/4)/(1 - z^-1)
% so the coefficients of the numerator and denominator are
num_coeff = [-1/4 0 0 0 1/4];
den_coeff = [1 -1];
% this filter can be used using the filter() function

% Designing the filter in fixed point aritmetic
iir = dfilt.df2;
set(iir, 'arithmetic', 'fixed', ...
    'OutputMode', 'SpecifyPrecision', ...
    'Numerator', num_coeff, ...
    'Denominator', den_coeff, ...
    'InputWordLength',16, ...            
    'InputFracLength', 0, ...            
    'OutputWordLength', 16, ...           
    'OutputFracLength', 2, ...
    'StateWordLength', 16, ...        
    'StateFracLength', 0, ...
    'ProductMode', 'SpecifyPrecision', ...
    'ProductWordLength', 18, ...
    'NumProdFracLength', 2, ...
    'DenProdFracLength', 2, ...
    'AccumMode', 'SpecifyPrecision', ...
    'AccumWordLength', 18, ...
    'NumAccumFracLength', 2, ...
    'DenAccumFracLength', 2, ...
    'CastBeforeSum', false);

% check the frequency response of the filter
fvtool(iir);


%% Test with audio signals

% Read the audio samples from the WAV file as int16 array
[example1_original, Fs_example1] = audioread('wav/file_example_WAV_5MG.wav', 'native');
[example2_original, Fs_example2] = audioread('wav/sample4.wav', 'native');

% Convert the int16 audio samples into 16 bit signed fixed values
example1_fix = fi(example1_original, true, 16, 0);
example2_fix = fi(example2_original, true, 16, 0);

% Filter the audio signal
example1_filtered_fix = filter(iir, example1_fix);
example2_filtered_fix = filter(iir, example2_fix);

% Save the filtered audio in a WAV file
audiowrite('wav/Example1Filtered.wav', int16(example1_filtered_fix), Fs_example1);
audiowrite('wav/Example2Filtered.wav', int16(example2_filtered_fix), Fs_example2);

%% Save data for testbenches in txt files

buildTxtFiles('sample1', example1_fix, example1_filtered_fix);
buildTxtFiles('sample2', example2_fix, example2_filtered_fix);